version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4
      
    steps:
      - checkout
      - run: yarn add
      - run: yarn test